Output assets/demo-volume.gif

Set Shell "zsh"
Set FontSize 18
Set Width 1200
Set Height 650
Set Padding 20
Set WindowBar Colorful
Set WindowBarSize 40
Set BorderRadius 8
Set Theme "Dracula"
Set TypingSpeed 60ms

Type `clear`
Enter
Sleep 500ms
Type `yp "로파이 재즈 힙합"`
Enter
Sleep 8s
Enter
Sleep 1500ms
Type "0"
Sleep 400ms
Type "0"
Sleep 400ms
Type "0"
Sleep 800ms
Type "9"
Sleep 400ms
Type "9"
Sleep 800ms
Type "q"
Sleep 500ms
Enter
Sleep 500ms
